// Turns the artwork in art/ into the assets the app ships.
//
//   node tools/art.mjs        (npm run art)
//
// Drop a file in art/ named after the asset it becomes: rank-6-topg.png,
// cup-winter.png, feat-streak30.png. It is downscaled to the size that asset
// appears at, written to www/img/, added to the service worker's precache list
// and the cache version is bumped.
//
// PNG in, PNG out, with only node:zlib: the repo has no image dependency and is
// not getting one. A .webp is passed through untouched, because nothing here
// can encode one and every export tool can. WebP is about a quarter the size,
// so it is worth asking for.

import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { decodePng, encodePng, resize } from './png.mjs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const SRC = root + 'art/';
const OUT = root + 'www/img/';
const SW = root + 'www/sw.js';
const MANIFEST = root + 'www/js/artwork.js';

/* ---------------- what each family is for ---------------- */

// Ranks and cups are heroes as well as badges; a feat medal never exceeds 44px.
// A share banner is not square and is drawn to cover, so it goes through as
// sent: 1080x1350 is what the card wants and the budget says the rest.
const FAMILIES = [
  { match: /^rank-/, size: 384, budget: 60000 },
  { match: /^cup-/, size: 384, budget: 70000 },
  { match: /^mark-/, size: 512, budget: 90000 },
  { match: /^feat-/, size: 128, budget: 20000 },
  { match: /^share-/, pass: true, budget: 300000 },
];

const familyOf = (name) => FAMILIES.find((f) => f.match.test(name));
const kb = (n) => `${(n / 1024).toFixed(1)}KB`;

/* ---------------- run ---------------- */

if (!existsSync(SRC)) {
  console.log(`Nothing to do: ${SRC} does not exist.\nDrop artwork in there named after the asset, e.g. rank-6-topg.png.`);
  process.exit(0);
}
mkdirSync(OUT, { recursive: true });

const files = readdirSync(SRC).filter((f) => /\.(png|webp)$/i.test(f));
if (!files.length) {
  console.log('art/ holds no .png or .webp files.');
  process.exit(0);
}

const written = [];
const problems = [];

for (const file of files.sort()) {
  const name = file.replace(/\.(png|webp)$/i, '');
  const family = familyOf(name);
  if (!family) {
    problems.push(`${file}: name it rank-*, cup-*, mark-*, feat-* or share-*. See docs/ART.md.`);
    continue;
  }
  const src = readFileSync(SRC + file);

  if (family.pass || /\.webp$/i.test(file)) {
    const ext = /\.webp$/i.test(file) ? 'webp' : 'png';
    writeFileSync(`${OUT}${name}.${ext}`, src);
    written.push({ name: `${name}.${ext}`, bytes: src.length, note: 'passed through' });
    if (src.length > family.budget) {
      problems.push(`${name}.${ext} is ${kb(src.length)}, over the ${kb(family.budget)} budget. Send it as WebP.`);
    }
    continue;
  }

  try {
    const { width, height, rgba } = decodePng(src);
    const out = encodePng(family.size, resize(rgba, width, height, family.size));
    writeFileSync(`${OUT}${name}.png`, out);
    const pad = width === height ? '' : ', padded';
    written.push({ name: `${name}.png`, bytes: out.length, note: `${width}x${height} to ${family.size}px${pad}` });
    if (out.length > family.budget) {
      problems.push(`${name}.png is ${kb(out.length)}, over the ${kb(family.budget)} budget. Export it as .webp instead and it will be about a quarter of that.`);
    }
  } catch (e) {
    problems.push(`${file}: ${e.message}`);
  }
}

/* The app asks for an asset by name, not by filename: a badge sent as a PNG and
   later replaced by a WebP must not need a code change. The map is generated
   rather than looked up at runtime, so it costs no request. */
function writeManifest() {
  const all = readdirSync(OUT).filter((f) => /\.(png|webp)$/i.test(f)).sort();
  const pairs = all.map((f) => `  '${f.replace(/\.(png|webp)$/i, '')}': '${f}',`).join('\n');
  writeFileSync(MANIFEST, `// Generated by tools/art.mjs. Do not edit: run \`npm run art\`.\n` +
    `// Asset name to the file that holds it, so the extension is the tool's problem.\n\n` +
    `export const ARTWORK = {\n${pairs}\n};\n\n` +
    `export const artSrc = (name) => (ARTWORK[name] ? \`./img/\${ARTWORK[name]}\` : '');\n`);
}

/* The service worker precaches by name, so a new asset has to be listed and the
   cache version has to move or nobody who already has the app will see it. A
   listed file that no longer exists is worse than a missing one: cache.addAll
   rejects on the first 404 and the whole install fails. */
function syncSw() {
  // Share banners are left out on purpose: half a megabyte of artwork nobody
  // sees until they open a card, and the card draws its own background when
  // one is missing. Everything else is on screen the moment the app opens.
  const have = new Set(readdirSync(OUT).filter((f) => /\.(png|webp)$/i.test(f) && !/^share-/.test(f)));
  let sw = readFileSync(SW, 'utf8');
  const listed = [...sw.matchAll(/^\s*'\.\/img\/([^']+)',\n/gm)];
  const stale = listed.filter((m) => !have.has(m[1]));
  const fresh = [...have].sort().filter((f) => !listed.some((m) => m[1] === f));
  if (!stale.length && !fresh.length) return;

  for (const m of stale) sw = sw.replace(m[0], '');
  if (fresh.length) {
    const anchor = "  // Crests. Precached: one arriving late leaves a hole where the screen is.\n";
    const block = fresh.map((n) => `  './img/${n}',\n`).join('');
    sw = sw.includes(anchor) ? sw.replace(anchor, anchor + block) : sw.replace("  './img/", block + "  './img/");
  }
  const version = Number(sw.match(/habit-nemesis-v(\d+)/)[1]) + 1;
  sw = sw.replace(/habit-nemesis-v\d+/, `habit-nemesis-v${version}`);
  writeFileSync(SW, sw);
  console.log(`sw.js: ${fresh.length} added, ${stale.length} dropped, cache bumped to habit-nemesis-v${version}`);
}

if (written.length) {
  writeManifest();
  syncSw();
}

console.log(`\n${written.length} written to www/img/`);
for (const w of written) console.log(`  ${w.name.padEnd(26)} ${kb(w.bytes).padStart(8)}  ${w.note}`);
if (problems.length) {
  console.log(`\n${problems.length} to look at:`);
  for (const p of problems) console.log(`  ${p}`);
}
