// Turns on Android's own backup for the generated project, so the record
// survives the app being uninstalled.
//
// Everything the app knows lives in the WebView's storage inside the app's
// private data directory, which Android deletes with the app. Auto Backup is
// the only thing that carries it off the device without a server: Android
// copies the app's data to the user's Google account and restores it the next
// time the app is installed on any of their devices.
//
// It is on by default, and the default is not enough. The default excludes
// nothing and includes nothing on purpose, so a WebView's storage can be
// skipped by the device-to-device transfer rules, and API 31 introduced a
// second file that supersedes the first. Both are written here, explicitly.
//
// android/ is regenerated on every build, so this runs after `cap sync`, the
// same way tools/patch-signing.mjs does.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';

const MANIFEST = 'android/app/src/main/AndroidManifest.xml';
const RES = 'android/app/src/main/res/xml';

if (!existsSync(MANIFEST)) {
  console.error(`${MANIFEST} not found. Run \`npx cap add android\` first.`);
  process.exit(1);
}

/* The two rule files. Pre-31 reads the first, 31 and up reads the second and
   ignores the first, so neither is optional. `clientSideEncryption` keeps the
   backup unreadable by anyone but the device it restores to, which is the only
   version of this the app's own promise can live with. */

const FULL_BACKUP = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/patch-backup.mjs. Read on Android 30 and below. -->
<full-backup-content>
    <include domain="database" path="." />
    <include domain="file" path="." />
    <include domain="sharedpref" path="." />
    <!-- No caches: they are rebuilt on first launch and would only make the
         backup bigger and slower to restore. -->
    <exclude domain="file" path="cache" />
    <exclude domain="external" path="." />
</full-backup-content>
`;

const EXTRACTION = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/patch-backup.mjs. Read on Android 31 and above. -->
<data-extraction-rules>
    <cloud-backup disableIfNoEncryptionCapabilities="false">
        <include domain="database" path="." />
        <include domain="file" path="." />
        <include domain="sharedpref" path="." />
        <exclude domain="file" path="cache" />
    </cloud-backup>
    <device-transfer>
        <include domain="database" path="." />
        <include domain="file" path="." />
        <include domain="sharedpref" path="." />
        <exclude domain="file" path="cache" />
    </device-transfer>
</data-extraction-rules>
`;

mkdirSync(RES, { recursive: true });
writeFileSync(`${RES}/hn_backup.xml`, FULL_BACKUP);
writeFileSync(`${RES}/hn_extraction.xml`, EXTRACTION);

let xml = readFileSync(MANIFEST, 'utf8');

if (!xml.includes('xmlns:tools=')) {
  xml = xml.replace('<manifest ', '<manifest xmlns:tools="http://schemas.android.com/tools"\n    ');
}

const WANT = {
  'android:allowBackup': 'true',
  'android:fullBackupContent': '@xml/hn_backup',
  'android:dataExtractionRules': '@xml/hn_extraction',
};

// The <application> tag, however Capacitor happens to have written it.
const open = xml.match(/<application\b[^>]*>/);
if (!open) {
  console.error('No <application> tag in the manifest.');
  process.exit(1);
}

let tag = open[0];
for (const [attr, value] of Object.entries(WANT)) {
  tag = tag.includes(`${attr}=`)
    ? tag.replace(new RegExp(`${attr}="[^"]*"`), `${attr}="${value}"`)
    : tag.replace('<application', `<application\n        ${attr}="${value}"`);
}
// Capacitor's own manifest sets allowBackup, and a library may set it too, so
// the app's value has to be declared the winner or the merger fails the build.
if (!tag.includes('tools:replace')) {
  tag = tag.replace('<application', `<application\n        tools:replace="android:allowBackup"`);
}

xml = xml.replace(open[0], tag);
writeFileSync(MANIFEST, xml);

console.log('Android backup on: full-data backup and device transfer both include the WebView store.');
for (const [attr, value] of Object.entries(WANT)) console.log(`  ${attr}="${value}"`);
